import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding Healthcare Manager Database...');

  // Password hash for all demo users: "password123"
  const passwordHash = await bcrypt.hash('password123', 10);

  // 1. Create Admin User
  const admin = await prisma.user.upsert({
    where: { email: 'admin@clinic.com' },
    update: {},
    create: {
      email: 'admin@clinic.com',
      password: passwordHash,
      name: 'System Admin',
      role: 'ADMIN',
      phone: '+1-555-0100'
    }
  });
  console.log(`✅ Admin created: ${admin.email}`);

  // 2. Create Doctor Users & Profiles
  const doctorData = [
    {
      name: 'Dr. Sarah Jenkins',
      email: 'sarah.jenkins@clinic.com',
      specialization: 'Cardiology',
      bio: 'Board certified cardiologist with over 12 years of experience in cardiovascular health.',
      workingHoursStart: '09:00',
      workingHoursEnd: '17:00',
      slotDurationMins: 30
    },
    {
      name: 'Dr. Michael Chen',
      email: 'michael.chen@clinic.com',
      specialization: 'Dermatology',
      bio: 'Specialist in clinical dermatology, skin cancer screening, and chronic skin conditions.',
      workingHoursStart: '08:30',
      workingHoursEnd: '16:30',
      slotDurationMins: 30
    },
    {
      name: 'Dr. Emily Rodriguez',
      email: 'emily.rodriguez@clinic.com',
      specialization: 'Pediatrics',
      bio: 'Dedicated pediatrician focused on adolescent medicine and developmental care.',
      workingHoursStart: '10:00',
      workingHoursEnd: '18:00',
      slotDurationMins: 30
    },
    {
      name: 'Dr. David Patel',
      email: 'david.patel@clinic.com',
      specialization: 'General Medicine',
      bio: 'Primary care physician providing comprehensive health evaluations and preventive care.',
      workingHoursStart: '09:00',
      workingHoursEnd: '17:00',
      slotDurationMins: 30
    }
  ];

  const createdDoctors = [];
  for (const doc of doctorData) {
    const user = await prisma.user.upsert({
      where: { email: doc.email },
      update: {},
      create: {
        email: doc.email,
        password: passwordHash,
        name: doc.name,
        role: 'DOCTOR',
        phone: '+1-555-0200',
        doctorProfile: {
          create: {
            specialization: doc.specialization,
            bio: doc.bio,
            workingHoursStart: doc.workingHoursStart,
            workingHoursEnd: doc.workingHoursEnd,
            slotDurationMins: doc.slotDurationMins
          }
        }
      },
      include: { doctorProfile: true }
    });
    createdDoctors.push(user);
    console.log(`✅ Doctor created: ${doc.name} (${doc.specialization})`);
  }

  // 3. Create Patient Users
  const patientData = [
    { name: 'John Doe', email: 'john.doe@example.com', phone: '+1-555-0301' },
    { name: 'Jane Smith', email: 'jane.smith@example.com', phone: '+1-555-0302' },
    { name: 'Alice Johnson', email: 'alice.johnson@example.com', phone: '+1-555-0303' }
  ];

  const createdPatients = [];
  for (const pat of patientData) {
    const user = await prisma.user.upsert({
      where: { email: pat.email },
      update: {},
      create: {
        email: pat.email,
        password: passwordHash,
        name: pat.name,
        role: 'PATIENT',
        phone: pat.phone
      }
    });
    createdPatients.push(user);
    console.log(`✅ Patient created: ${pat.name}`);
  }

  // 4. Create Sample Appointments & AI Summaries
  const todayStr = new Date().toISOString().split('T')[0];
  const drJenkins = createdDoctors[0].doctorProfile!;
  const patientJohn = createdPatients[0];

  const sampleAppt = await prisma.appointment.create({
    data: {
      patientId: patientJohn.id,
      doctorId: drJenkins.id,
      appointmentDate: todayStr,
      startTime: '10:00',
      endTime: '10:30',
      status: 'BOOKED',
      symptoms: 'Experiencing mild chest tightness after exercise and occasional palpitations over the last 3 days.'
    }
  });

  await prisma.preVisitSummary.create({
    data: {
      appointmentId: sampleAppt.id,
      urgency: 'Medium',
      chiefComplaint: 'Chest tightness after exercise and palpitations (3 days duration).',
      suggestedQuestions: JSON.stringify([
        'Does the tightness radiate to the arm or neck?',
        'How long do the palpitation episodes typically last?',
        'Have you taken any over-the-counter anti-inflammatories recently?'
      ]),
      rawLlmOutput: 'Generated by Gemini AI'
    }
  });

  console.log('🎉 Database seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
